### ISSUE TITLE
Ability to setup which remote to go to?

### ISSUE THREAD

**Issue by jeregrine** [github-flow/github-flow#14]
For some reason when I do "git hub-feature review|publish [branchname]" its chose a non-origin remote. Is there are a way around this?

**Comment by DavidSouther** [comment]
It's looking for whatever property is configured in "git config --get github-flow.origin"

I'm working on some documentation on how to configure github-flow without using the clone scripts.

**Comment by jeregrine** [comment]
Cool. Sooner the better, its pretty annoying to use whenever I'm working
with my orgs repos... :)

**Comment by DavidSouther** [comment]
There is now a configuration section in the README on the three project-level configuration options `github-flow` uses.

**Comment by jeregrine** [comment]
Thank you so much!
