### ISSUE TITLE
Is this currently working?

### ISSUE THREAD

**Issue by neilcronin** [github-flow/github-flow#18]
Hi, 
I get random dumps of json from, presumably, github.com running this.  Is this supposed to work on a current Mac?  Or is it a washed away sand castle?  Thanks!

$ git hub-clone neilcronin/githubflow.git
{
  "message": "Bad credentials"
}

$ git hub-clone neilcronin/githubflow.git
{
  "message": "Max number of login attempt exceeded"
}

tia,
-n

**Comment by DavidSouther** [comment]
Looks like your credentials that got saved when you first ran github-flow are no longer correct.

Try deleting `~/.github_token`, that should prompt reauthentication.

**Comment by DavidSouther** [comment]
Also check the value of the username stored in github-flow.username in the global config.

**Comment by pseudomuto** [comment]
I agree with @DavidSouther, it smells like an issue with auth/request limits.

If you're really stuck, you could delete ~/.ghf and ~/.github_token and do a fresh install (as defined in the README). This would ask you to login again to create your auth token.
